export const button: string;
export const buttonBack: string;
export const buttonNext: string;
export const dot: string;
export const dots: string;
export const footer: string;
export const img: string;
export const innerSlide: string;
export const slider: string;
